/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StaffManager;

import Class.SetUpCloseOperation;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class EnterToSearch extends javax.swing.JFrame {

    /**
     * Creates new form EnterToSearch
     */
    
    private String label;
    private SearchNV parentFrame;
    
    public EnterToSearch() {
        initComponents();
        SetUpCloseOperation.applyCloseOperation(this);
    }
    
    public EnterToSearch(String label, SearchNV parentFrame) {
        this.label = label;
        this.parentFrame = parentFrame;
        initComponents();
        SetUpCloseOperation.applyCloseOperation(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        XacNhan = new javax.swing.JButton();
        Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhập thông tin");

        XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        XacNhan.setText("Xác nhận");
        XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhanActionPerformed(evt);
            }
        });

        Huy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Huy.setText("Hủy");
        Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(XacNhan)
                        .addGap(69, 69, 69)
                        .addComponent(Huy)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XacNhan)
                    .addComponent(Huy))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XacNhanActionPerformed
                                                
        // Lấy dữ liệu từ text field
        String data = jTextField1.getText();

        // Kiểm tra xem dữ liệu có trống hay không
        if (data.trim().isEmpty()) {
            // Nếu trống, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin!", "Message", JOptionPane.ERROR_MESSAGE);
            return; // Dừng lại không tiếp tục xử lý
        }

        // Kiểm tra xem nhãn của nút được nhấn là gì
        if (label.equals("Tuổi")) {
            // Kiểm tra xem dữ liệu có đúng định dạng số không
            try {
                int age = Integer.parseInt(data);
                // Gửi dữ liệu cho SearchNV
                parentFrame.processSearchData(label, String.valueOf(age));
                // Đóng cửa sổ hiện tại
                this.dispose();
            } catch (NumberFormatException e) {
                // Nếu không đúng định dạng số, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Nhập sai định dạng, vui lòng nhập lại!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Nếu không phải là tuổi, gửi dữ liệu cho SearchNV như bình thường
            parentFrame.processSearchData(label, data);
            // Đóng cửa sổ hiện tại
            this.dispose();
    
        }   

    }//GEN-LAST:event_XacNhanActionPerformed

    private void HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyActionPerformed
        // TODO add your handling code here:
        // Đóng cửa sổ hiện tại nếu nhấn nút "Hủy"
        
        this.dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterToSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterToSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterToSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterToSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterToSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Huy;
    private javax.swing.JButton XacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
