/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StaffManager;

import Class.NhanVien;
import Class.FileIO;
import Class.SetUpCloseOperation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Class.MyController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import Start.MainMenu;


/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {
    
    public List<NhanVien> list = new ArrayList<>();
    
    public List<NhanVien> getList() {
        return this.list;
    }
    
    public void setList(List<NhanVien> list) {
        this.list = list;
    }
    
    DefaultTableModel model;
    MyController controller = new MyController();
    public String FILE_NAME = "src\\NhanVien.txt";

    /**
     * Creates new form NewJFrame
     */
    @Override
    public void dispose() {
        super.dispose();
        // Ghi dữ liệu vào file trước khi đóng cửa sổ
        if (!list.isEmpty()) {
            FileIO.writeToFile(list, FILE_NAME);
        }
    }

    public Main() {
        initComponents();
        SetUpCloseOperation.applyCloseOperation(this);
        
        list = FileIO.readFromFile(FILE_NAME);
        refreshList();
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Ghi dữ liệu vào file trước khi đóng cửa sổ
                FileIO.writeToFile(list, FILE_NAME);
            }
        });
    }
    
    public Main(List<NhanVien> list) {
        if (list != null) {
            this.list = list;
        } else {
            this.list = FileIO.readFromFile(FILE_NAME);
        }
        initComponents();
        SetUpCloseOperation.applyCloseOperation(this);
        refreshList();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Save data to file before closing window
                FileIO.writeToFile(Main.this.list, FILE_NAME);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addNV = new javax.swing.JButton();
        deleteNV = new javax.swing.JButton();
        sortNV = new javax.swing.JButton();
        fixNV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Return = new javax.swing.JButton();
        searchNV = new javax.swing.JButton();
        ChamCong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý Nhân viên");
        setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách nhân viên");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addNV.setText("Thêm");
        addNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        addNV.setVerifyInputWhenFocusTarget(false);
        addNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNVActionPerformed(evt);
            }
        });

        deleteNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteNV.setText("Xóa");
        deleteNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        deleteNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNVActionPerformed(evt);
            }
        });

        sortNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sortNV.setText("Sắp xếp");
        sortNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        sortNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortNVActionPerformed(evt);
            }
        });

        fixNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fixNV.setText("Sửa");
        fixNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        fixNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixNVActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Nhân viên", "Tên Nhân viên", "Tuổi", "Địa chỉ", "Giới tính", "Chức vụ", "Hệ số lương", "Số ngày công"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Return.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Return.setText("Quay lại trang chủ");
        Return.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        searchNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchNV.setText("Tìm kiếm");
        searchNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        searchNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNVActionPerformed(evt);
            }
        });

        ChamCong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChamCong.setText("Chấm công");
        ChamCong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        ChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamCongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(deleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fixNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortNV, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(searchNV, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refreshList() {
        model = (DefaultTableModel) jTable1.getModel();

        // Xóa hết các dòng trong bảng
        model.setRowCount(0);

        int stt = 1;
        for (NhanVien nv : list) {
            // Tạo một mảng chứa thông tin của mỗi nhân viên
            Object[] row = new Object[]{
                stt,
                nv.getMa(),
                nv.getTen(),
                nv.getTuoi(),
                nv.getDiaChi(),
                nv.getGioiTinh(),
                nv.getChucVu(),
                nv.getHeSoLuong(),
                nv.getSoNgayCong()
            };
            // Thêm mảng vào model của bảng
            model.addRow(row);
            stt++;
        }
    }
    private void addNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNVActionPerformed
        // TODO add your handling code here:
        dispose();
        AddNV addNVFrame = new AddNV(this);
        addNVFrame.setVisible(true);
        addNVFrame.setDSNV(list);
        list = addNVFrame.getDSNV();
        refreshList();
        
    }//GEN-LAST:event_addNVActionPerformed
    
    private void deleteNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNVActionPerformed
        // TODO add your handling code here:
        dispose();
        DeleteNV deleteNVFrame = new DeleteNV(this);
        deleteNVFrame.setVisible(true);
        deleteNVFrame.setDSNV(list);
        list = deleteNVFrame.getDSNV();
        refreshList();
    }//GEN-LAST:event_deleteNVActionPerformed

    private void sortNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNVActionPerformed
        // TODO add your handling code here:
        dispose();
        SortNV sortNVFrame = new SortNV(this);
        sortNVFrame.setVisible(true);
    }//GEN-LAST:event_sortNVActionPerformed

    private void fixNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixNVActionPerformed
        // TODO add your handling code here:
        dispose();
        FixNV fixNVFrame = new FixNV(this);
        fixNVFrame.setVisible(true);
        fixNVFrame.setDSNV(list);
        list = fixNVFrame.getDSNV();
        refreshList();
        
    }//GEN-LAST:event_fixNVActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ReturnActionPerformed

    private void searchNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNVActionPerformed
        // TODO add your handling code here:
        dispose();
        SearchNV searchNVFrame = new SearchNV(this);
        searchNVFrame.setVisible(true);
        
    }//GEN-LAST:event_searchNVActionPerformed

    private void ChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamCongActionPerformed
        // TODO add your handling code here:
        dispose();
        Timekeeping timekeepingFrame = new Timekeeping(this);
        timekeepingFrame.setVisible(true);
        timekeepingFrame.setDSNV(list);
        list = timekeepingFrame.getDSNV();
        refreshList();
    }//GEN-LAST:event_ChamCongActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChamCong;
    private javax.swing.JButton Return;
    private javax.swing.JButton addNV;
    private javax.swing.JButton deleteNV;
    private javax.swing.JButton fixNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchNV;
    private javax.swing.JButton sortNV;
    // End of variables declaration//GEN-END:variables

    
}
